#import <Foundation/Foundation.h>
#import "OS_Object.h"

/**
* Boats
* ## Authentication  Basic Authentication is required for all requests.
*
* OpenAPI spec version: 1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/




@protocol OS_BoatImage
@end

@interface OS_BoatImage : OS_Object


@property(nonatomic) NSNumber* _id;

@property(nonatomic) NSNumber* boatId;

@property(nonatomic) NSString* uRL;

@property(nonatomic) NSString* fILENAME;

@property(nonatomic) NSNumber* iSFEATURED;

@end
