#import <Foundation/Foundation.h>
#import "OS_Object.h"

/**
* Boats
* ## Authentication  Basic Authentication is required for all requests.
*
* OpenAPI spec version: 1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "OS_Boat.h"
#import "OS_BoatImage.h"


@protocol OS_BoatBoatImageRecord
@end

@interface OS_BoatBoatImageRecord : OS_Object


@property(nonatomic) OS_Boat* boat;

@property(nonatomic) OS_BoatImage* boatImage;

@end
