#import <Foundation/Foundation.h>
#import "OS_Object.h"

/**
* Boats
* ## Authentication  Basic Authentication is required for all requests.
*
* OpenAPI spec version: 1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/




@protocol OS_Boat
@end

@interface OS_Boat : OS_Object


@property(nonatomic) NSNumber* _id;

@property(nonatomic) NSString* nAME;

@property(nonatomic) NSString* mAKE;

@property(nonatomic) NSString* mODEL;

@property(nonatomic) NSNumber* yEAR;

@property(nonatomic) NSString* cONDITION;

@property(nonatomic) NSString* tYPE;

@property(nonatomic) NSString* cLASS;

@property(nonatomic) NSString* lENGTH;

@property(nonatomic) NSString* fUELTYPE;

@property(nonatomic) NSString* hULLMATERIAL;

@property(nonatomic) NSString* lOCATION;

@property(nonatomic) NSString* lOA;

@property(nonatomic) NSString* bEAM;

@property(nonatomic) NSString* mAXDRAFT;

@property(nonatomic) NSString* dISPLACEMENT;

@property(nonatomic) NSString* bALLAST;

@property(nonatomic) NSString* eNGINETYPE;

@property(nonatomic) NSString* eNGINEMAKE;

@property(nonatomic) NSString* eNGINEMODEL;

@property(nonatomic) NSNumber* eNGINEYEAR;

@property(nonatomic) NSString* pOWER;

@property(nonatomic) NSString* dRIVERTYPE;

@property(nonatomic) NSString* hREF;

@property(nonatomic) NSString* sAPID;

@property(nonatomic) NSNumber* lATITUDE;

@property(nonatomic) NSNumber* lONGITUDE;

@property(nonatomic) NSString* dROPBOXPATH;

@property(nonatomic) NSNumber* price;

@property(nonatomic) NSString* sFId;

@property(nonatomic) NSNumber* isActive;

@end
